title-meta: "Assignment 1"
date-meta: \today
author-meta: "Emilia Dunfelt"
reference-section-title: References
documentclass: article
classoption:
- a4paper
- 12pt
- titlepage
- dvipsnames
geometry:
- left=1in
- right=1in
- bottom=1in
- top=1in
